# Generated by Django 5.0.4 on 2024-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/avatars/default.svg', help_text='Аватар пользователя. Если пользователь не                                          заполняет это поле, то устанавливается стандартный аватар', upload_to='users/avatars', verbose_name='аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Адресс электронной почты. Является логином, потому уникален', max_length=254, unique=True, verbose_name='почта'),
        ),
    ]
