# Generated by Django 5.0.4 on 2024-04-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0004_alter_payment_course_alter_payment_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='сумма оплаты'),
        ),
    ]
