# Generated by Django 5.0.4 on 2024-05-07 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0006_course_user_lesson_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'платёж', 'verbose_name_plural': 'платежи'},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Описание курса', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preview',
            field=models.ImageField(default='learning_materials/course/preview/default/course.svg', help_text='Фото, которое будет выбрано системой как превью-фото курса', upload_to='learning_materials/course/preview/', verbose_name='превью фото'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Название курса', max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, добавивший курс', on_delete=django.db.models.deletion.CASCADE, related_name='course', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(help_text='ссылка на модель курса', on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='learning_materials.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(help_text='Описание урока.', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(default='learning_materials/lesson/preview/default/lesson.svg', help_text='Фото-превью урока', upload_to='learning_materials/lesson/preview/', verbose_name='Превью фото'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='Название курса', max_length=50, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='user',
            field=models.ForeignKey(help_text='ссылка на модель пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(blank=True, help_text='Видео курса. содержит основной контент', null=True, verbose_name='ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=8, help_text='Сумма оплаты за курс или урок', max_digits=16, verbose_name='сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Ссылка на курс, по которому была произведена оплата.                                отсутствие означает, что оплата была произведена за урок', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='learning_materials.course', verbose_name='оплаченный курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Ссылка на урок, по которому была произведена оплата.                                отсутствие означает, что оплата была произведена за курс', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='learning_materials.lesson', verbose_name='оплаченный урок'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'payment in cash'), ('TRNS', 'payment by transfer to the account')], help_text='Метод оплаты: CASH - наличные, TRNS - переводом на счёт', max_length=4, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата оплаты за курс', verbose_name='дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(help_text='ссылка на модель пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(auto_now_add=True, help_text='время, с которого пользователь подписан на курс', verbose_name='время подписки')),
                ('course', models.ForeignKey(help_text='курс на который была оформлена подписка', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='learning_materials.course', verbose_name='курс')),
                ('user', models.ForeignKey(help_text='пользователь, оформивший подписку на курс', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь, оформивший подписку')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
            },
        ),
    ]
