# Generated by Django 5.0.4 on 2024-05-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_materials', '0008_subscription_unique_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id'], 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-id'], 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
    ]
